# HW 4

Question 1: Write a Python/NumPy code block that finds the distinct/unique common items between these two arrays

The approach I took was to use the intersection function which does this.

In [14]:
import numpy as np

#Here are the arrays refereneced in the question
a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])

#Here is the solution
print(np.intersect1d(b, a))

[2 4]


Question 2:Create the following 5x3 array using knowledge you have of Python’s / NumPy’s sequencing functionality so that you do not need to explicitly key in every integer value.

I did this by reshaping a normal array into  a 3x5 and the Transforming it so that it would fit the layout in the example which is not pictured here.

In [2]:
#Task 2

print(np.arange(1,16).reshape(3,5).T)

[[ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]
 [ 5 10 15]]


Question 3: Write a Python/Numpy code block that removes from array a any items that are also present in array b

My approach was to use the in1d function which is a test whether each element of an array is also present in a second array. I then inversed this function using the "logical not" function to get our desired result.

In [11]:
#Task 3
a = np.array([12, 5, 7, 15, 3, 1, 8])
b = np.array([14, 6, 3, 11, 19, 12, 5])

a[np.logical_not(np.in1d(a, b))]

array([ 7, 15,  1,  8])

Question 4:
Suppose you have ridden a bicycle from New York City to Key West, Florida. Your bicycle odometer shows the total miles you have travelled thus far, which you make a note of each day with paper and pencil. Your first two entries might be ‘55’ and ‘120’, indicating that you rode your bike 55 miles on day 1 and 65 miles on day 2. Your task is to create a NumPy array wherein you can record the cumulative miles you recorded each day during your trip. Then use your Python skills to show the total miles that you rode each day. Assume the trip took a total of 35 days and included at least 4 non-consecutive days where no cycling was possible due to either weather conditions or personal fatigue/soreness. For the remaining 31 days, you would have covered the entire distance between NYC and Key West. Complete your work within your Jupyter Notebook for this assignment and be sure to include a writeup explaining your approach to this problem, including the ways in which you decided to make use of NumPy.

My approach was to use the random function to generate a "day" of bike riding which can vary around the average amount of distance needed to be traveled over the 31 days of travel given. 

Data for how many miles was generated by google maps for a biking path, 130 miles were omitted from this schedule since they are taken on a ferry and are relativly quick. 

This method also omits days with 0 miles traveled since calculating this would go against the purpose of the program as it is designed to generate a random day of biking and on a break day there is no such trip.

Data is tracked in two independent methods: there is the "trip" which is the bike trip of that given day, and there is the "odimter" which is the running sum of the miles traveled.

A random "day" of bike riding was estimated as 1422/31 = 45 as the average, randomly generated days fall within a confidance interval around this average. The confidance interval was chosen through testing and is between 44 and 50 miles per day.



In [26]:
#Task 4
import numpy as np

trip = []
days = 31
odmiter = []


for i in range(days):
    #if we already reach the destination we don't want
    # to keep creating new trips. to stop this I used an
    # if statement.
    if sum(trip)<1422:
        
        #Generate the bikeing trip for the day and 
        #store them in a variable
        miles_on_that_day = np.random.randint(44, 50)
        
        #Append the variable into a list "trip"
        trip.append(miles_on_that_day)
        
        #create the running sum for the miles traveled 
        # each day
        odmiter = [odmiter, sum(trip)]

print(sum(trip))
print(odmiter)

1445
[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[], 48], 97], 141], 189], 237], 283], 332], 376], 422], 466], 511], 559], 606], 653], 700], 747], 796], 841], 890], 935], 983], 1031], 1077], 1123], 1171], 1216], 1263], 1308], 1353], 1400], 1445]


Question 5: Using the NumPy array that has been loaded for you in the Jupyter Notebook, answer the following questions using
NumPy’s slicing, methods, and functions:

In [24]:
# This Code block is to import the data for this question
# you can ignore it


import pandas
import numpy as np

# supress scientific notation
np.set_printoptions(suppress = True)

# read the data file from GitHub and convert to a NumPy ndarray object
nyc_water = pandas.read_csv('https://raw.githubusercontent.com/jtopor/DAV-5400/master/Week4/Water_Consumption_In_The_New_York_City.csv').as_matrix()

# verify you have an ndarray object
type(nyc_water)



C:\Users\enwwe\Anaconda3\lib\site-packages\ipykernel_launcher.py:9: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  if __name__ == '__main__':


numpy.ndarray

In [8]:
## What is the maximum yearly NYC consumption of water in millions of gallons per day?

np.max(nyc_water[:,2])

1512.0

Part A) How many calendar years are represented within this data set? NumPy's shape command is one way to find out.


In [27]:
#Show the shape of the first column
np.shape(nyc_water[:,0])

(39,)

Part B) What is the mean and the standard deviation of the per capita daily water consumption?


In [28]:
#Show the mean and standard dev of column 3

print(np.mean(nyc_water[:,3]))
print(np.std(nyc_water[:,3]))

160.30769230769232
31.51894330370624


What is the increase or decrease in population from year to year? Use NumPy's `diff` function to create an array
of differences and save that to a variable called "pop_diff", then print that variable to the screen.


In [29]:
#Show the diff YoY
pop_diff = np.diff(nyc_water[:,1])
print(pop_diff)

[-30461.   17602.   19864.   72119.   53290.   39540.   45192.   23230.
  11243.   -9544.   -8525.   38851.   54443.   77222.   64292.   62582.
  64772.   75631.   84816.   89401.   60618.   16685.5  16685.5  16685.5
  16685.5  16685.5  16685.5  16685.5  16685.5  16685.5  16685.5 108965.
  77081.   61281.   49530.   44512.   21171.   85025. ]
